### PR TITLE
Add repo dependencies to spec.

### PR DESCRIPTION
**Pull request by EmmaTheMartian**

### CODE REVIEW

**Review by realeatham — CHANGES_REQUESTED** [review]
this should be in a new version of the spec not overriding the old one

**Comment by EmmaTheMartian** [comment]
> this should be in a new version of the spec not overriding the old one

That's a good point

**Review by realeatham — APPROVED** [review]

**Comment by EmmaTheMartian** [comment]
Are we good to merge?

**Comment by Mr-Zombii** [comment]
looks like it

**Pull request merged**
